# Generated by Django 6.1 on 2026-08-17 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('college_type', models.CharField(choices=[('GOVT', 'Government'), ('GOVT_AIDED', 'Government Aided'), ('UNIV_DEPT', 'University Department'), ('SELF_FIN', 'Self-Financing')], default='SELF_FIN', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(choices=[('OC', 'OC - Open Category'), ('BC', 'BC - Backward Class'), ('BCM', 'BCM - Backward Class Muslim'), ('MBC', 'MBC/DNC - Most Backward Class'), ('SC', 'SC - Scheduled Caste'), ('SCA', 'SCA - Scheduled Caste Arunthathiyar'), ('ST', 'ST - Scheduled Tribe')], max_length=5)),
                ('cutoff_mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='counseling.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='counseling.college')),
            ],
            options={
                'ordering': ['-cutoff_mark'],
                'unique_together': {('college', 'branch', 'community', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(choices=[('OC', 'OC - Open Category'), ('BC', 'BC - Backward Class'), ('BCM', 'BCM - Backward Class Muslim'), ('MBC', 'MBC/DNC - Most Backward Class'), ('SC', 'SC - Scheduled Caste'), ('SCA', 'SCA - Scheduled Caste Arunthathiyar'), ('ST', 'ST - Scheduled Tribe')], default='OC', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('cutoff_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('ALLOTTED', 'Allotted')], default='SAVED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cutoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counseling.cutoff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='counseling.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'cutoff')},
            },
        ),
    ]
